<?php
// database/seeders/ProviderSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProviderSeeder extends Seeder
{
    /**
     * Real providers exported from the live bahali.org database,
     * with their grouped support areas (provider_support_areas pivot).
     *
     * NOTE: run UserSeeder first — each provider links to a user_id.
     * File paths in verification_document / profile_photo point to the
     * original uploads under storage/app/public; copy those files across
     * if you want the images/documents to resolve.
     */
    public function run(): void
    {
        // ---- Provider #1 — Dr. Smith ----
        $providerId = DB::table('providers')->insertGetId([
            'user_id' => 2,
            'provider_type' => 'individual',
            'organization_name' => 'Dr. Smith',
            'credentials' => 'Phd',
            'professional_title' => json_encode(['Clinical Psychologist', 'Addiction Medicine Specialist', 'Clinical Social Worker']),
            'professional_title_other' => null,
            'short_bio' => 'dfghjjj',
            'years_experience' => '2–5 years',
            'license_number' => null,
            'license_states' => json_encode(['Anguilla', 'United Kingdom']),
            'license_status' => 'not_applicable',
            'verification_document' => 'providers/verification/KElZ8YL99kkxIbXlQmrEAAeed5Z8DY53y8HbNQ2N.jpg',
            'populations_served' => json_encode(['Infants & Toddlers (0–5)', 'Adults (26–64)', 'Caregivers']),
            'caribbean_identity' => 'yes',
            'caribbean_experience' => 'yes',
            'languages' => json_encode(['English', 'Jamaican Patois']),
            'languages_other' => null,
            'cultural_approach' => '454566',
            'service_formats' => json_encode(['Virtual']),
            'practice_settings' => json_encode(['Private Practice']),
            'address' => '9 Tyler Ave.,',
            'city' => 'Hempstead',
            'state_province' => 'Blowing Point',
            'country' => 'Anguilla',
            'multiple_locations' => 'yes',
            'hide_address' => true,
            'telehealth_regions' => json_encode(['Aruba', 'Anguilla']),
            'payment_methods' => json_encode(['Self-Pay']),
            'insurance_plans' => null,
            'phone' => '5164690040',
            'website' => null,
            'social_links' => null,
            'profile_photo' => 'providers/photos/W1aIovqizgBMGJEBUw9M1OnmcjKxdrn1bgrhZKRp.jpg',
            'additional_photos' => json_encode([]),
            'accessibility' => json_encode(['Home Visits Available', 'Interpreter Available']),
            'status' => 'approved',
            'note' => null,
            'consent_accurate' => true,
            'consent_notify' => true,
            'consent_no_endorsement' => true,
            'consent_public' => true,
            'reviewed_at' => '2026-07-13 02:47:50',
            'created_at' => '2026-07-13 02:40:39',
            'updated_at' => '2026-07-13 02:47:50',
        ]);

        DB::table('provider_support_areas')->insert([
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Anxiety & Worry',
                'created_at' => '2026-07-13 02:40:39',
                'updated_at' => '2026-07-13 02:40:39',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Depression & Low Mood',
                'created_at' => '2026-07-13 02:40:39',
                'updated_at' => '2026-07-13 02:40:39',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Relationships & Family',
                'area' => 'Couples & Relationship Counseling',
                'created_at' => '2026-07-13 02:40:39',
                'updated_at' => '2026-07-13 02:40:39',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Children, Teens & Families',
                'area' => 'Child Behavioral Challenges',
                'created_at' => '2026-07-13 02:40:39',
                'updated_at' => '2026-07-13 02:40:39',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Children, Teens & Families',
                'area' => 'ADHD',
                'created_at' => '2026-07-13 02:40:39',
                'updated_at' => '2026-07-13 02:40:39',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Children, Teens & Families',
                'area' => 'Social Skills',
                'created_at' => '2026-07-13 02:40:39',
                'updated_at' => '2026-07-13 02:40:39',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Women\'s Health & Wellness',
                'area' => 'Postpartum Depression',
                'created_at' => '2026-07-13 02:40:39',
                'updated_at' => '2026-07-13 02:40:39',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Older Adults & Aging',
                'area' => 'Healthy Aging & Older Adult Well-Being',
                'created_at' => '2026-07-13 02:40:39',
                'updated_at' => '2026-07-13 02:40:39',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Older Adults & Aging',
                'area' => 'Retirement & Life Changes',
                'created_at' => '2026-07-13 02:40:39',
                'updated_at' => '2026-07-13 02:40:39',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Health & Everyday Wellness',
                'area' => 'Living with Chronic Illness',
                'created_at' => '2026-07-13 02:40:39',
                'updated_at' => '2026-07-13 02:40:39',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Health & Everyday Wellness',
                'area' => 'Sleep & Insomnia',
                'created_at' => '2026-07-13 02:40:39',
                'updated_at' => '2026-07-13 02:40:39',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Work, School & Daily Life',
                'area' => 'Workplace Stress',
                'created_at' => '2026-07-13 02:40:39',
                'updated_at' => '2026-07-13 02:40:39',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Culture, Faith & Community',
                'area' => 'Church & Ministry Support',
                'created_at' => '2026-07-13 02:40:39',
                'updated_at' => '2026-07-13 02:40:39',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Culture, Faith & Community',
                'area' => 'LGBTQIA+ Support',
                'created_at' => '2026-07-13 02:40:39',
                'updated_at' => '2026-07-13 02:40:39',
            ],
        ]);

        // ---- Provider #2 — Dr. Tyana Ruiz ----
        $providerId = DB::table('providers')->insertGetId([
            'user_id' => 3,
            'provider_type' => 'individual',
            'organization_name' => 'Dr. Tyana Ruiz',
            'credentials' => 'PsyD',
            'professional_title' => json_encode(['Clinical Psychologist']),
            'professional_title_other' => null,
            'short_bio' => 'Hello. My name is Dr. Tyana Ruiz and I am a clinical psychologist specializing in trauma and sleep-related disorders. I enjoy working with diverse individuals who each come from unique backgrounds and provide trauma-informed and culturally competent care.',
            'years_experience' => '2–5 years',
            'license_number' => 'PY12993',
            'license_states' => json_encode(['United States']),
            'license_status' => 'active',
            'verification_document' => 'providers/verification/LkS2yLiiAdXdiW2tJdVq0Und97VAkPUaKhBuKmCE.pdf',
            'populations_served' => json_encode(['Adults (26–64)', 'Young Adults (18–25)', 'Older Adults (65+)', 'Veterans', 'Helping Professionals']),
            'caribbean_identity' => 'no',
            'caribbean_experience' => 'yes',
            'languages' => json_encode(['English']),
            'languages_other' => null,
            'cultural_approach' => 'I enjoy making a space for individuals to discuss cultural factors and make sure to integrate this throughout our work together. I consult and read into various cultural considerations as needed but ultimately, let the client guide me through their perspective of their real lived experience. Part of cultural consideration to me is having a curious and open discussion on how culture or other diverse factors have impacted the individual.',
            'service_formats' => json_encode(['Virtual', 'In-Person', 'Hybrid']),
            'practice_settings' => json_encode(['Government Agency', 'Hospital / Health System']),
            'address' => '504 Fourth Ave S Apt. 3',
            'city' => 'St. Petersburg',
            'state_province' => 'Florida',
            'country' => 'United States',
            'multiple_locations' => 'no',
            'hide_address' => true,
            'telehealth_regions' => json_encode(['United States']),
            'payment_methods' => json_encode(['Sliding Scale', 'Self-Pay']),
            'insurance_plans' => null,
            'phone' => '7142707781',
            'website' => null,
            'social_links' => null,
            'profile_photo' => 'providers/photos/jRsdphEHMvOlBnZHflzKpTK8xrFiWyDONXClv4pN.jpg',
            'additional_photos' => json_encode([]),
            'accessibility' => json_encode(['Other']),
            'status' => 'approved',
            'note' => 'Provider profile approved and verified',
            'consent_accurate' => true,
            'consent_notify' => true,
            'consent_no_endorsement' => true,
            'consent_public' => true,
            'reviewed_at' => '2026-07-16 22:05:51',
            'created_at' => '2026-07-14 12:57:14',
            'updated_at' => '2026-07-16 22:05:51',
        ]);

        DB::table('provider_support_areas')->insert([
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Life Changes & Transitions',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Managing Emotions',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Trauma & Recovery',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Depression & Low Mood',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Stress & Burnout',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Anxiety & Worry',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Grief & Loss',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Men\'s Health & Wellness',
                'area' => 'Men\'s Emotional Wellness',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Men\'s Health & Wellness',
                'area' => 'Identity & Purpose',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Men\'s Health & Wellness',
                'area' => 'Relationship Challenges',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Crisis, Trauma & Recovery',
                'area' => 'Crisis Support',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Crisis, Trauma & Recovery',
                'area' => 'Disaster Recovery',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Crisis, Trauma & Recovery',
                'area' => 'Support for Helping Professionals',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Crisis, Trauma & Recovery',
                'area' => 'Community Violence',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Crisis, Trauma & Recovery',
                'area' => 'Self-Harm Recovery',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Crisis, Trauma & Recovery',
                'area' => 'Suicide Prevention',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Crisis, Trauma & Recovery',
                'area' => 'Support for First Responders',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Health & Everyday Wellness',
                'area' => 'Sleep & Insomnia',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Health & Everyday Wellness',
                'area' => 'Stress Management',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Health & Everyday Wellness',
                'area' => 'Lifestyle Changes',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Work, School & Daily Life',
                'area' => 'Vicarious Trauma',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Culture, Faith & Community',
                'area' => 'LGBTQIA+ Support',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Culture, Faith & Community',
                'area' => 'Cultural Identity & Belonging',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Culture, Faith & Community',
                'area' => 'Experiences of Racism & Discrimination',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Culture, Faith & Community',
                'area' => 'Immigration & Adjusting to a New Culture',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Culture, Faith & Community',
                'area' => 'Faith & Spiritual Support',
                'created_at' => '2026-07-14 12:57:14',
                'updated_at' => '2026-07-14 12:57:14',
            ],
        ]);

        // ---- Provider #3 — Trissina Smith ----
        $providerId = DB::table('providers')->insertGetId([
            'user_id' => 4,
            'provider_type' => 'individual',
            'organization_name' => 'Trissina Smith',
            'credentials' => 'PhD',
            'professional_title' => json_encode(['Clinical Psychologist', 'Clinical Social Worker', 'Board Certified Behavior Analyst (BCBA)', 'Other (specify)']),
            'professional_title_other' => 'Testing',
            'short_bio' => 'Testing purposes.',
            'years_experience' => '11–15 years',
            'license_number' => '123456',
            'license_states' => json_encode(['Jamaica']),
            'license_status' => 'active',
            'verification_document' => null,
            'populations_served' => json_encode(['Parents', 'Couples', 'Families']),
            'caribbean_identity' => 'yes',
            'caribbean_experience' => 'yes',
            'languages' => json_encode(['English']),
            'languages_other' => null,
            'cultural_approach' => 'Testing',
            'service_formats' => json_encode(['In-Person', 'Virtual']),
            'practice_settings' => json_encode(['Private Practice', 'Community Agency']),
            'address' => '123 Main St',
            'city' => 'Maine',
            'state_province' => 'New York',
            'country' => 'United States',
            'multiple_locations' => 'yes',
            'hide_address' => false,
            'telehealth_regions' => json_encode(['Bermuda']),
            'payment_methods' => json_encode(['No-Cost Services']),
            'insurance_plans' => null,
            'phone' => '51612345678',
            'website' => null,
            'social_links' => null,
            'profile_photo' => 'providers/photos/k3O4PSWoA6hDZeQ5IF2EdM5MV43a1Ml1O7BLcIL0.jpg',
            'additional_photos' => json_encode([]),
            'accessibility' => json_encode(['Wheelchair Accessible']),
            'status' => 'approved',
            'note' => 'Reviewed and Approved',
            'consent_accurate' => true,
            'consent_notify' => true,
            'consent_no_endorsement' => true,
            'consent_public' => true,
            'reviewed_at' => '2026-07-17 16:27:46',
            'created_at' => '2026-07-14 18:59:00',
            'updated_at' => '2026-07-17 16:27:46',
        ]);

        DB::table('provider_support_areas')->insert([
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Anxiety & Worry',
                'created_at' => '2026-07-14 18:59:00',
                'updated_at' => '2026-07-14 18:59:00',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Managing Emotions',
                'created_at' => '2026-07-14 18:59:00',
                'updated_at' => '2026-07-14 18:59:00',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Life Changes & Transitions',
                'created_at' => '2026-07-14 18:59:00',
                'updated_at' => '2026-07-14 18:59:00',
            ],
        ]);

        // ---- Provider #4 — Dr. Hannah Long ----
        $providerId = DB::table('providers')->insertGetId([
            'user_id' => 5,
            'provider_type' => 'individual',
            'organization_name' => 'Dr. Hannah Long',
            'credentials' => 'PsyD',
            'professional_title' => json_encode(['Clinical Psychologist']),
            'professional_title_other' => null,
            'short_bio' => 'I\'m Dr. Long, and I have a strong passion for helping others during their hard moments.',
            'years_experience' => '2–5 years',
            'license_number' => '.0107012587',
            'license_states' => json_encode(['United States']),
            'license_status' => 'active',
            'verification_document' => null,
            'populations_served' => json_encode(['Young Adults (18–25)', 'Adults (26–64)', 'Older Adults (65+)', 'Caregivers', 'Parents', 'Couples', 'Veterans', 'Families', 'Faith Leaders & Clergy', 'Educators', 'Helping Professionals', 'Community Leaders']),
            'caribbean_identity' => 'no',
            'caribbean_experience' => 'no',
            'languages' => json_encode(['English']),
            'languages_other' => null,
            'cultural_approach' => null,
            'service_formats' => json_encode(['Virtual']),
            'practice_settings' => json_encode(['Private Practice']),
            'address' => '1503 Red Briar Way',
            'city' => 'Jonesboro',
            'state_province' => 'Georgia',
            'country' => 'United States',
            'multiple_locations' => 'no',
            'hide_address' => false,
            'telehealth_regions' => json_encode([]),
            'payment_methods' => json_encode(['Self-Pay']),
            'insurance_plans' => null,
            'phone' => '3096427591',
            'website' => null,
            'social_links' => null,
            'profile_photo' => 'providers/photos/zij0gPb7gfi4mzyrh2Dp1OBzxIa5PprxDupjTbrG.png',
            'additional_photos' => json_encode([]),
            'accessibility' => json_encode(['Other']),
            'status' => 'approved',
            'note' => 'Reviewed and Approved',
            'consent_accurate' => true,
            'consent_notify' => true,
            'consent_no_endorsement' => true,
            'consent_public' => true,
            'reviewed_at' => '2026-07-17 16:23:05',
            'created_at' => '2026-07-15 01:15:24',
            'updated_at' => '2026-07-17 16:23:05',
        ]);

        DB::table('provider_support_areas')->insert([
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Grief & Loss',
                'created_at' => '2026-07-15 01:15:24',
                'updated_at' => '2026-07-15 01:15:24',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Life Changes & Transitions',
                'created_at' => '2026-07-15 01:15:24',
                'updated_at' => '2026-07-15 01:15:24',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Managing Emotions',
                'created_at' => '2026-07-15 01:15:24',
                'updated_at' => '2026-07-15 01:15:24',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Depression & Low Mood',
                'created_at' => '2026-07-15 01:15:24',
                'updated_at' => '2026-07-15 01:15:24',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Relationships & Family',
                'area' => 'Family Conflict',
                'created_at' => '2026-07-15 01:15:24',
                'updated_at' => '2026-07-15 01:15:24',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Relationships & Family',
                'area' => 'Blended Families',
                'created_at' => '2026-07-15 01:15:24',
                'updated_at' => '2026-07-15 01:15:24',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Children, Teens & Families',
                'area' => 'Big Feelings & Emotional Regulation',
                'created_at' => '2026-07-15 01:15:24',
                'updated_at' => '2026-07-15 01:15:24',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Women\'s Health & Wellness',
                'area' => 'Postpartum Depression',
                'created_at' => '2026-07-15 01:15:24',
                'updated_at' => '2026-07-15 01:15:24',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Women\'s Health & Wellness',
                'area' => 'Infertility',
                'created_at' => '2026-07-15 01:15:24',
                'updated_at' => '2026-07-15 01:15:24',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Women\'s Health & Wellness',
                'area' => 'Menopause & Midlife',
                'created_at' => '2026-07-15 01:15:24',
                'updated_at' => '2026-07-15 01:15:24',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Women\'s Health & Wellness',
                'area' => 'Postpartum Anxiety',
                'created_at' => '2026-07-15 01:15:24',
                'updated_at' => '2026-07-15 01:15:24',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Women\'s Health & Wellness',
                'area' => 'Pregnancy & Infant Loss',
                'created_at' => '2026-07-15 01:15:24',
                'updated_at' => '2026-07-15 01:15:24',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Women\'s Health & Wellness',
                'area' => 'Pregnancy Support',
                'created_at' => '2026-07-15 01:15:24',
                'updated_at' => '2026-07-15 01:15:24',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Men\'s Health & Wellness',
                'area' => 'Identity & Purpose',
                'created_at' => '2026-07-15 01:15:24',
                'updated_at' => '2026-07-15 01:15:24',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Older Adults & Aging',
                'area' => 'Grief & Loss in Later Life',
                'created_at' => '2026-07-15 01:15:24',
                'updated_at' => '2026-07-15 01:15:24',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Older Adults & Aging',
                'area' => 'Coping with Chronic Illness',
                'created_at' => '2026-07-15 01:15:24',
                'updated_at' => '2026-07-15 01:15:24',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Crisis, Trauma & Recovery',
                'area' => 'Psychological First Aid',
                'created_at' => '2026-07-15 01:15:24',
                'updated_at' => '2026-07-15 01:15:24',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Crisis, Trauma & Recovery',
                'area' => 'Suicide Prevention',
                'created_at' => '2026-07-15 01:15:24',
                'updated_at' => '2026-07-15 01:15:24',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Crisis, Trauma & Recovery',
                'area' => 'Crisis Support',
                'created_at' => '2026-07-15 01:15:24',
                'updated_at' => '2026-07-15 01:15:24',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Health & Everyday Wellness',
                'area' => 'Sleep & Insomnia',
                'created_at' => '2026-07-15 01:15:24',
                'updated_at' => '2026-07-15 01:15:24',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Health & Everyday Wellness',
                'area' => 'Stress Management',
                'created_at' => '2026-07-15 01:15:24',
                'updated_at' => '2026-07-15 01:15:24',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Substance Use & Recovery',
                'area' => 'Substance Use',
                'created_at' => '2026-07-15 01:15:24',
                'updated_at' => '2026-07-15 01:15:24',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Work, School & Daily Life',
                'area' => 'Career Changes',
                'created_at' => '2026-07-15 01:15:24',
                'updated_at' => '2026-07-15 01:15:24',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Work, School & Daily Life',
                'area' => 'Vicarious Trauma',
                'created_at' => '2026-07-15 01:15:24',
                'updated_at' => '2026-07-15 01:15:24',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Culture, Faith & Community',
                'area' => 'LGBTQIA+ Support',
                'created_at' => '2026-07-15 01:15:24',
                'updated_at' => '2026-07-15 01:15:24',
            ],
        ]);

        // ---- Provider #5 — Kelsey Thomas ----
        $providerId = DB::table('providers')->insertGetId([
            'user_id' => 6,
            'provider_type' => 'individual',
            'organization_name' => 'Kelsey Thomas',
            'credentials' => 'PhD',
            'professional_title' => json_encode(['Clinical Psychologist']),
            'professional_title_other' => null,
            'short_bio' => 'Test bio',
            'years_experience' => '2–5 years',
            'license_number' => null,
            'license_states' => json_encode(['United States']),
            'license_status' => 'active',
            'verification_document' => null,
            'populations_served' => json_encode(['Young Adults (18–25)', 'Older Adults (65+)', 'Adults (26–64)', 'Veterans']),
            'caribbean_identity' => 'no',
            'caribbean_experience' => 'no',
            'languages' => json_encode(['English']),
            'languages_other' => null,
            'cultural_approach' => null,
            'service_formats' => json_encode(['Virtual', 'Hybrid', 'In-Person', 'Group-Based']),
            'practice_settings' => json_encode(['Hospital / Health System', 'Government Agency']),
            'address' => '133 test street',
            'city' => 'Test',
            'state_province' => 'West Virginia',
            'country' => 'United States',
            'multiple_locations' => 'yes',
            'hide_address' => true,
            'telehealth_regions' => json_encode(['United States']),
            'payment_methods' => json_encode(['Self-Pay', 'Pro Bono / Volunteer Services']),
            'insurance_plans' => null,
            'phone' => '555-555-5555',
            'website' => null,
            'social_links' => null,
            'profile_photo' => 'providers/photos/8Iwh3MwDnb5XzGhI7MCfnwLYaVSmQgdkdFyVAYI4.jpg',
            'additional_photos' => json_encode([]),
            'accessibility' => json_encode(['Other']),
            'status' => 'approved',
            'note' => 'Reviewed and approved',
            'consent_accurate' => true,
            'consent_notify' => true,
            'consent_no_endorsement' => true,
            'consent_public' => true,
            'reviewed_at' => '2026-07-17 16:21:29',
            'created_at' => '2026-07-16 00:28:59',
            'updated_at' => '2026-07-17 16:21:29',
        ]);

        DB::table('provider_support_areas')->insert([
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Trauma & Recovery',
                'created_at' => '2026-07-16 00:28:59',
                'updated_at' => '2026-07-16 00:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Depression & Low Mood',
                'created_at' => '2026-07-16 00:28:59',
                'updated_at' => '2026-07-16 00:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Anxiety & Worry',
                'created_at' => '2026-07-16 00:28:59',
                'updated_at' => '2026-07-16 00:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Stress & Burnout',
                'created_at' => '2026-07-16 00:28:59',
                'updated_at' => '2026-07-16 00:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Panic Attacks',
                'created_at' => '2026-07-16 00:28:59',
                'updated_at' => '2026-07-16 00:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Managing Emotions',
                'created_at' => '2026-07-16 00:28:59',
                'updated_at' => '2026-07-16 00:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Crisis, Trauma & Recovery',
                'area' => 'Suicide Prevention',
                'created_at' => '2026-07-16 00:28:59',
                'updated_at' => '2026-07-16 00:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Crisis, Trauma & Recovery',
                'area' => 'Self-Harm Recovery',
                'created_at' => '2026-07-16 00:28:59',
                'updated_at' => '2026-07-16 00:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Children, Teens & Families',
                'area' => 'ADHD',
                'created_at' => '2026-07-16 00:28:59',
                'updated_at' => '2026-07-16 00:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Children, Teens & Families',
                'area' => 'Social Skills',
                'created_at' => '2026-07-16 00:28:59',
                'updated_at' => '2026-07-16 00:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Substance Use & Recovery',
                'area' => 'Alcohol Use',
                'created_at' => '2026-07-16 00:28:59',
                'updated_at' => '2026-07-16 00:28:59',
            ],
        ]);

        // ---- Provider #6 — Harvest Tabernacle ----
        $providerId = DB::table('providers')->insertGetId([
            'user_id' => 7,
            'provider_type' => 'faith_based',
            'organization_name' => 'Harvest Tabernacle',
            'credentials' => 'Pastor',
            'professional_title' => json_encode(['Pastoral Counselor']),
            'professional_title_other' => null,
            'short_bio' => 'I am pastor Raymond Boswell, the Shepherd at Harvest Tabernacle',
            'years_experience' => '20+ years',
            'license_number' => null,
            'license_states' => json_encode(['Jamaica']),
            'license_status' => 'active',
            'verification_document' => null,
            'populations_served' => json_encode(['Older Adults (65+)', 'Caregivers', 'Parents', 'Couples']),
            'caribbean_identity' => 'yes',
            'caribbean_experience' => 'yes',
            'languages' => json_encode(['English', 'Jamaican Patois']),
            'languages_other' => null,
            'cultural_approach' => 'By using the word as the guide',
            'service_formats' => json_encode(['In-Person', 'Group-Based']),
            'practice_settings' => json_encode(['Faith-Based Setting']),
            'address' => '9 Portmore Street',
            'city' => 'Portmore',
            'state_province' => 'St. Catherine',
            'country' => 'Jamaica',
            'multiple_locations' => 'no',
            'hide_address' => false,
            'telehealth_regions' => json_encode(['Jamaica']),
            'payment_methods' => json_encode(['No-Cost Services', 'Donation-Based']),
            'insurance_plans' => null,
            'phone' => '8133336841',
            'website' => 'https://harvesttab.org',
            'social_links' => null,
            'profile_photo' => 'providers/photos/EotNQAYZkJDzLjyj9KJ54N7gTtBlPy8chXAlOq1p.png',
            'additional_photos' => json_encode([]),
            'accessibility' => json_encode(['Wheelchair Accessible', 'Public Transportation Accessible']),
            'status' => 'approved',
            'note' => null,
            'consent_accurate' => true,
            'consent_notify' => true,
            'consent_no_endorsement' => true,
            'consent_public' => true,
            'reviewed_at' => '2026-07-20 01:41:52',
            'created_at' => '2026-07-19 14:43:51',
            'updated_at' => '2026-07-20 01:41:52',
        ]);

        DB::table('provider_support_areas')->insert([
            [
                'provider_id' => $providerId,
                'category' => 'Relationships & Family',
                'area' => 'Couples & Relationship Counseling',
                'created_at' => '2026-07-19 14:43:51',
                'updated_at' => '2026-07-19 14:43:51',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Relationships & Family',
                'area' => 'Premarital Counseling',
                'created_at' => '2026-07-19 14:43:51',
                'updated_at' => '2026-07-19 14:43:51',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Relationships & Family',
                'area' => 'Healing from Relationship Abuse',
                'created_at' => '2026-07-19 14:43:51',
                'updated_at' => '2026-07-19 14:43:51',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Children, Teens & Families',
                'area' => 'Child Behavioral Challenges',
                'created_at' => '2026-07-19 14:43:51',
                'updated_at' => '2026-07-19 14:43:51',
            ],
        ]);

        // ---- Provider #7 — EDEMI ----
        $providerId = DB::table('providers')->insertGetId([
            'user_id' => 8,
            'provider_type' => 'faith_based',
            'organization_name' => 'EDEMI',
            'credentials' => 'Spiritual Leader',
            'professional_title' => json_encode(['Other (specify)']),
            'professional_title_other' => 'Deliverance Minister',
            'short_bio' => 'I am the shepherd of the deliverance ministry',
            'years_experience' => '20+ years',
            'license_number' => null,
            'license_states' => json_encode(['British Virgin Islands']),
            'license_status' => 'not_applicable',
            'verification_document' => 'providers/verification/dfeRVWBpTvdUm0cyCpiklkPgVbmJl877Jcffvx9f.png',
            'populations_served' => json_encode(['Infants & Toddlers (0–5)', 'Adolescents (13–17)', 'Adults (26–64)', 'Parents', 'Couples', 'Families', 'Caregivers', 'Older Adults (65+)', 'Young Adults (18–25)', 'Children (6–12)', 'Faith Leaders & Clergy']),
            'caribbean_identity' => 'yes',
            'caribbean_experience' => 'yes',
            'languages' => json_encode(['English', 'Jamaican Patois']),
            'languages_other' => null,
            'cultural_approach' => 'We honor the word in all we do while treating the whole person',
            'service_formats' => json_encode(['In-Person', 'Hybrid', 'Virtual']),
            'practice_settings' => json_encode(['Faith-Based Setting']),
            'address' => '23 Red Hills Road',
            'city' => 'Road Town',
            'state_province' => 'Tortola',
            'country' => 'British Virgin Islands',
            'multiple_locations' => 'yes',
            'hide_address' => false,
            'telehealth_regions' => json_encode(['Other']),
            'payment_methods' => json_encode(['Donation-Based']),
            'insurance_plans' => null,
            'phone' => '8133336841',
            'website' => null,
            'social_links' => null,
            'profile_photo' => 'providers/photos/bOMD5NJDoLctEMyiIE1UZUtcWRElGZMHVxZRjX1O.png',
            'additional_photos' => json_encode([]),
            'accessibility' => json_encode(['Wheelchair Accessible', 'Public Transportation Accessible']),
            'status' => 'approved',
            'note' => null,
            'consent_accurate' => true,
            'consent_notify' => true,
            'consent_no_endorsement' => true,
            'consent_public' => true,
            'reviewed_at' => '2026-07-20 01:39:14',
            'created_at' => '2026-07-19 15:06:34',
            'updated_at' => '2026-07-20 01:39:14',
        ]);

        DB::table('provider_support_areas')->insert([
            [
                'provider_id' => $providerId,
                'category' => 'Culture, Faith & Community',
                'area' => 'Church & Ministry Support',
                'created_at' => '2026-07-19 15:06:34',
                'updated_at' => '2026-07-19 15:06:34',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Culture, Faith & Community',
                'area' => 'Faith & Spiritual Support',
                'created_at' => '2026-07-19 15:06:34',
                'updated_at' => '2026-07-19 15:06:34',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Relationships & Family',
                'area' => 'Couples & Relationship Counseling',
                'created_at' => '2026-07-19 15:06:34',
                'updated_at' => '2026-07-19 15:06:34',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Relationships & Family',
                'area' => 'Divorce & Separation',
                'created_at' => '2026-07-19 15:06:34',
                'updated_at' => '2026-07-19 15:06:34',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Relationships & Family',
                'area' => 'Communication Challenges',
                'created_at' => '2026-07-19 15:06:34',
                'updated_at' => '2026-07-19 15:06:34',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Relationships & Family',
                'area' => 'Healing from Relationship Abuse',
                'created_at' => '2026-07-19 15:06:34',
                'updated_at' => '2026-07-19 15:06:34',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Relationships & Family',
                'area' => 'Marriage Counseling',
                'created_at' => '2026-07-19 15:06:34',
                'updated_at' => '2026-07-19 15:06:34',
            ],
        ]);

        // ---- Provider #8 — Youth For Kids ----
        $providerId = DB::table('providers')->insertGetId([
            'user_id' => 9,
            'provider_type' => 'support_group',
            'organization_name' => 'Youth For Kids',
            'credentials' => 'Youth Counsellor',
            'professional_title' => json_encode(['Other (specify)']),
            'professional_title_other' => 'Youth Counsellor',
            'short_bio' => 'We keep children out of trouble',
            'years_experience' => '11–15 years',
            'license_number' => null,
            'license_states' => json_encode(['Bahamas']),
            'license_status' => 'active',
            'verification_document' => null,
            'populations_served' => json_encode(['Adolescents (13–17)']),
            'caribbean_identity' => 'yes',
            'caribbean_experience' => 'yes',
            'languages' => json_encode(['English']),
            'languages_other' => null,
            'cultural_approach' => 'We provoide a safe space',
            'service_formats' => json_encode(['In-Person', 'Group-Based']),
            'practice_settings' => json_encode(['Community Agency']),
            'address' => '12 Nassau Blvd',
            'city' => 'Nassau',
            'state_province' => 'New Providence/Nassau',
            'country' => 'Bahamas',
            'multiple_locations' => 'yes',
            'hide_address' => false,
            'telehealth_regions' => json_encode(['Other']),
            'payment_methods' => json_encode(['No-Cost Services']),
            'insurance_plans' => null,
            'phone' => '8133336841',
            'website' => null,
            'social_links' => null,
            'profile_photo' => 'providers/photos/Xo4G8nSO33cUzAu3CHurSVzsqiuf8IuM653Y1PbG.png',
            'additional_photos' => json_encode([]),
            'accessibility' => json_encode(['Wheelchair Accessible']),
            'status' => 'approved',
            'note' => null,
            'consent_accurate' => true,
            'consent_notify' => true,
            'consent_no_endorsement' => true,
            'consent_public' => true,
            'reviewed_at' => '2026-07-20 01:38:17',
            'created_at' => '2026-07-19 15:18:05',
            'updated_at' => '2026-07-20 01:38:17',
        ]);

        DB::table('provider_support_areas')->insert([
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Stress & Burnout',
                'created_at' => '2026-07-19 15:18:05',
                'updated_at' => '2026-07-19 15:18:05',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Building Self-Confidence',
                'created_at' => '2026-07-19 15:18:05',
                'updated_at' => '2026-07-19 15:18:05',
            ],
        ]);

        // ---- Provider #9 — We Stand With ----
        $providerId = DB::table('providers')->insertGetId([
            'user_id' => 10,
            'provider_type' => 'community_program',
            'organization_name' => 'We Stand With',
            'credentials' => null,
            'professional_title' => json_encode(['Psychiatric Mental Health Nurse Practitioner']),
            'professional_title_other' => null,
            'short_bio' => 'We provide psychiatric care to marginalized individuals',
            'years_experience' => 'Less than 2 years',
            'license_number' => null,
            'license_states' => json_encode(['Cayman Islands']),
            'license_status' => 'provisional',
            'verification_document' => null,
            'populations_served' => json_encode(['Infants & Toddlers (0–5)', 'Adults (26–64)']),
            'caribbean_identity' => 'prefer_not',
            'caribbean_experience' => 'no',
            'languages' => json_encode(['English']),
            'languages_other' => null,
            'cultural_approach' => 'By creating a judgment-free space for the individual',
            'service_formats' => json_encode(['In-Person']),
            'practice_settings' => json_encode(['Nonprofit Organization']),
            'address' => '123 Main Street',
            'city' => 'franklin',
            'state_province' => 'Nort di Salina',
            'country' => 'Bonaire',
            'multiple_locations' => 'yes',
            'hide_address' => false,
            'telehealth_regions' => json_encode(['Anguilla', 'Antigua and Barbuda']),
            'payment_methods' => json_encode(['Self-Pay']),
            'insurance_plans' => null,
            'phone' => '8133336841',
            'website' => 'https://bahali.org',
            'social_links' => 'Facebook.com/BahaliCircle, Instagram.com/BahaliCircle, Youtube.com/BahaliCircle',
            'profile_photo' => 'providers/photos/xXj4HXv8sapRY197TCEis4LvecRNzL237Oc1eh0E.jpg',
            'additional_photos' => json_encode([]),
            'accessibility' => json_encode(['Wheelchair Accessible', 'Public Transportation Accessible', 'Home Visits Available']),
            'status' => 'approved',
            'note' => null,
            'consent_accurate' => true,
            'consent_notify' => true,
            'consent_no_endorsement' => true,
            'consent_public' => true,
            'reviewed_at' => '2026-07-20 01:34:37',
            'created_at' => '2026-07-20 00:09:36',
            'updated_at' => '2026-07-20 01:34:37',
        ]);

        DB::table('provider_support_areas')->insert([
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Anxiety & Worry',
                'created_at' => '2026-07-20 00:09:36',
                'updated_at' => '2026-07-20 00:09:36',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Women\'s Health & Wellness',
                'area' => 'Pregnancy Support',
                'created_at' => '2026-07-20 00:09:36',
                'updated_at' => '2026-07-20 00:09:36',
            ],
        ]);

        // ---- Provider #10 — YES Community Center ----
        $providerId = DB::table('providers')->insertGetId([
            'user_id' => 11,
            'provider_type' => 'community_program',
            'organization_name' => 'YES Community Center',
            'credentials' => 'PhD, LCSW',
            'professional_title' => json_encode(['School Psychologist', 'Peer Support Specialist']),
            'professional_title_other' => null,
            'short_bio' => 'We create space for our young people so they can learn skills to thrive in all areas of their lives.',
            'years_experience' => null,
            'license_number' => '1234567',
            'license_states' => json_encode(['Haiti']),
            'license_status' => 'active',
            'verification_document' => null,
            'populations_served' => json_encode(['Adolescents (13–17)', 'Young Adults (18–25)']),
            'caribbean_identity' => 'yes',
            'caribbean_experience' => 'yes',
            'languages' => json_encode(['English', 'Haitian Creole', 'French']),
            'languages_other' => null,
            'cultural_approach' => 'By creating room for those who need guidance and support.',
            'service_formats' => json_encode(['In-Person', 'School-Based', 'Group-Based']),
            'practice_settings' => json_encode(['University', 'Faith-Based Setting']),
            'address' => '555 Brent Road',
            'city' => 'Port Au Prince',
            'state_province' => 'Nord-Est',
            'country' => 'Haiti',
            'multiple_locations' => 'yes',
            'hide_address' => false,
            'telehealth_regions' => json_encode(['Martinique', 'Guadeloupe']),
            'payment_methods' => json_encode(['Self-Pay', 'Sliding Scale', 'Pro Bono / Volunteer Services']),
            'insurance_plans' => null,
            'phone' => '8133336841',
            'website' => null,
            'social_links' => null,
            'profile_photo' => 'providers/photos/7En5Ml8ADOZ6gFBomTSfhqGwi4aNNjEmGXegU4i4.jpg',
            'additional_photos' => json_encode([]),
            'accessibility' => json_encode(['Wheelchair Accessible', 'Home Visits Available']),
            'status' => 'approved',
            'note' => null,
            'consent_accurate' => true,
            'consent_notify' => true,
            'consent_no_endorsement' => true,
            'consent_public' => true,
            'reviewed_at' => '2026-07-20 01:32:26',
            'created_at' => '2026-07-20 00:18:09',
            'updated_at' => '2026-07-20 01:32:26',
        ]);

        DB::table('provider_support_areas')->insert([
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Building Self-Confidence',
                'created_at' => '2026-07-20 00:18:09',
                'updated_at' => '2026-07-20 00:18:09',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Life Changes & Transitions',
                'created_at' => '2026-07-20 00:18:09',
                'updated_at' => '2026-07-20 00:18:09',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Culture, Faith & Community',
                'area' => 'Church & Ministry Support',
                'created_at' => '2026-07-20 00:18:09',
                'updated_at' => '2026-07-20 00:18:09',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Culture, Faith & Community',
                'area' => 'Experiences of Racism & Discrimination',
                'created_at' => '2026-07-20 00:18:09',
                'updated_at' => '2026-07-20 00:18:09',
            ],
        ]);
        // ---- Provider #11 — Razaul Karim ----
        $providerId = DB::table('providers')->insertGetId([
            'user_id' => 12,
            'provider_type' => 'individual',
            'organization_name' => 'Razaul Karim',
            'credentials' => 'PsyD',
            'professional_title' => json_encode(['Clinical Psychologist']),
            'professional_title_other' => null,
            'short_bio' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi cursus imperdiet arcu, non sagittis turpis fermentum at. Maecenas ac nisl semper, auctor lectus nec, sollicitudin lectus',
            'years_experience' => 'Less than 2 years',
            'license_number' => null,
            'license_states' => json_encode(['Antigua and Barbuda']),
            'license_status' => 'active',
            'verification_document' => 'providers/verification/BGs5LmtNoIylmst3BlY2Gf6Y9UFkqIObXbwW9Ed1.pdf',
            'populations_served' => json_encode(['Infants & Toddlers (0–5)', 'Children (6–12)']),
            'caribbean_identity' => 'no',
            'caribbean_experience' => 'no',
            'languages' => json_encode(['English']),
            'languages_other' => null,
            'cultural_approach' => null,
            'service_formats' => json_encode(['In-Person']),
            'practice_settings' => json_encode(['Private Practice']),
            'address' => 'Gcc 114/4, West Chatar, Bof',
            'city' => 'Gazipur',
            'state_province' => 'Culebra',
            'country' => 'Spanish Virgin Islands',
            'multiple_locations' => 'no',
            'hide_address' => true,
            'telehealth_regions' => json_encode(['Anguilla', 'Other']),
            'telehealth_regions_other' => 'Dhaka',
            'payment_methods' => json_encode(['Self-Pay']),
            'insurance_plans' => 'Aetna',
            'phone' => '01558918129',
            'website' => 'facebook.com',
            'social_links' => 'www.facebook.com',
            'profile_photo' => 'providers/photos/fnrsnyydWk0vVUpf3L3nuB8a8zHdo0nNrIxViKBz.png',
            'additional_photos' => json_encode([
                'providers/photos/eOpiTJl2vnU6MmgoUWW2tm9eZwzZtMJsJZ1MhCia.png',
                'providers/photos/lPxmZRkcfJA591BftgNCShDNVRkIzH0Hma04MY1F.png'
            ]),
            'accessibility' => json_encode(['Wheelchair Accessible']),
            'status' => 'approved',
            'note' => null,
            'consent_accurate' => true,
            'consent_notify' => true,
            'consent_no_endorsement' => true,
            'consent_public' => true,
            'reviewed_at' => '2026-07-22 02:05:10',
            'created_at' => '2026-07-21 13:24:08',
            'updated_at' => '2026-07-22 02:05:10',
        ]);

        DB::table('provider_support_areas')->insert([
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Anxiety & Worry',
                'created_at' => '2026-07-21 13:24:08',
                'updated_at' => '2026-07-21 13:24:08',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Relationships & Family',
                'area' => 'Healing from Relationship Abuse',
                'created_at' => '2026-07-21 13:24:08',
                'updated_at' => '2026-07-21 13:24:08',
            ],
        ]);

        // ---- Provider #12 — Dr. Gina Pasquale ----
        $providerId = DB::table('providers')->insertGetId([
            'user_id' => 13,
            'provider_type' => 'individual',
            'organization_name' => 'Dr. Gina Pasquale',
            'credentials' => 'PsyD',
            'professional_title' => json_encode(['Clinical Psychologist']),
            'professional_title_other' => null,
            'short_bio' => 'n/a',
            'years_experience' => '20+ years',
            'license_number' => '1190',
            'license_states' => json_encode(['United States']),
            'license_status' => 'active',
            'verification_document' => null,
            'populations_served' => json_encode([
                'Infants & Toddlers (0–5)',
                'Children (6–12)',
                'Adolescents (13–17)',
                'Young Adults (18–25)',
                'Older Adults (65+)',
                'Adults (26–64)',
                'Parents',
                'Caregivers',
                'Families',
                'Faith Leaders & Clergy',
                'Helping Professionals',
                'Community Leaders'
            ]),
            'caribbean_identity' => 'no',
            'caribbean_experience' => 'no',
            'languages' => json_encode(['English']),
            'languages_other' => null,
            'cultural_approach' => null,
            'service_formats' => json_encode(['Virtual']),
            'practice_settings' => json_encode(['Nonprofit Organization']),
            'address' => '23 Central Square',
            'city' => 'Keene',
            'state_province' => 'New Hampshire',
            'country' => 'United States',
            'multiple_locations' => 'no',
            'hide_address' => false,
            'telehealth_regions' => json_encode(['United States']),
            'telehealth_regions_other' => null,
            'payment_methods' => json_encode(['Insurance Accepted', 'Medicare', 'Medicaid', 'Pro Bono / Volunteer Services']),
            'insurance_plans' => null,
            'phone' => '6033552244',
            'website' => null,
            'social_links' => null,
            'profile_photo' => 'providers/photos/yWm1aVLesWiiCCB8B5DFu3caXeVuBVLs9MtmnNeN.jpg',
            'additional_photos' => json_encode([]),
            'accessibility' => json_encode(['Wheelchair Accessible']),
            'status' => 'approved',
            'note' => null,
            'consent_accurate' => true,
            'consent_notify' => true,
            'consent_no_endorsement' => true,
            'consent_public' => true,
            'reviewed_at' => '2026-07-22 02:03:12',
            'created_at' => '2026-07-22 01:28:59',
            'updated_at' => '2026-07-22 02:03:12',
        ]);

        DB::table('provider_support_areas')->insert([
            // Mental & Emotional Well-Being
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Anxiety & Worry',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Stress & Burnout',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Grief & Loss',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Depression & Low Mood',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Trauma & Recovery',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Obsessive Thoughts & Compulsive Behaviors (OCD)',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Life Changes & Transitions',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Managing Emotions',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
            // Relationships & Family
            [
                'provider_id' => $providerId,
                'category' => 'Relationships & Family',
                'area' => 'Parenting Support',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Relationships & Family',
                'area' => 'Family Conflict',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Relationships & Family',
                'area' => 'Caregiver Support',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Relationships & Family',
                'area' => 'Healing from Relationship Abuse',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
            // Women's Health & Wellness
            [
                'provider_id' => $providerId,
                'category' => 'Women\'s Health & Wellness',
                'area' => 'Menopause & Midlife',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Women\'s Health & Wellness',
                'area' => 'Postpartum Anxiety',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
            // Older Adults & Aging
            [
                'provider_id' => $providerId,
                'category' => 'Older Adults & Aging',
                'area' => 'Grief & Loss in Later Life',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Older Adults & Aging',
                'area' => 'Retirement & Life Changes',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Older Adults & Aging',
                'area' => 'Dementia Support',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Older Adults & Aging',
                'area' => 'Healthy Aging & Older Adult Well-Being',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Older Adults & Aging',
                'area' => 'Memory Concerns',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Older Adults & Aging',
                'area' => 'Alzheimer\'s Disease Support',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Older Adults & Aging',
                'area' => 'Coping with Chronic Illness',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
            // Crisis, Trauma & Recovery
            [
                'provider_id' => $providerId,
                'category' => 'Crisis, Trauma & Recovery',
                'area' => 'Support for Helping Professionals',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Crisis, Trauma & Recovery',
                'area' => 'Crisis Support',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
            // Culture, Faith & Community
            [
                'provider_id' => $providerId,
                'category' => 'Culture, Faith & Community',
                'area' => 'Faith & Spiritual Support',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Culture, Faith & Community',
                'area' => 'LGBTQIA+ Support',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Culture, Faith & Community',
                'area' => 'Cultural Identity & Belonging',
                'created_at' => '2026-07-22 01:28:59',
                'updated_at' => '2026-07-22 01:28:59',
            ],
        ]);

        // ---- Provider #13 — Dr. Becket ----
        $providerId = DB::table('providers')->insertGetId([
            'user_id' => 14,
            'provider_type' => 'individual',
            'organization_name' => 'Dr. Becket',
            'credentials' => 'PhD',
            'professional_title' => json_encode(['Neuropsychologist']),
            'professional_title_other' => null,
            'short_bio' => 'Test Bio',
            'years_experience' => '11–15 years',
            'license_number' => '1234567',
            'license_states' => json_encode(['United States']),
            'license_status' => 'provisional',
            'verification_document' => null,
            'populations_served' => json_encode(['Helping Professionals']),
            'caribbean_identity' => 'yes',
            'caribbean_experience' => 'yes',
            'languages' => json_encode(['English']),
            'languages_other' => null,
            'cultural_approach' => 'Test Section',
            'service_formats' => json_encode(['In-Person']),
            'practice_settings' => json_encode(['Nonprofit Organization']),
            'address' => '9 Tyler Ave.,',
            'city' => 'Hempstead',
            'state_province' => 'Saint Thomas',
            'country' => 'United States Virgin Islands',
            'multiple_locations' => 'yes',
            'hide_address' => false,
            'telehealth_regions' => json_encode(['Other']),
            'telehealth_regions_other' => 'St. Croix',
            'payment_methods' => json_encode(['Self-Pay']),
            'insurance_plans' => 'None',
            'phone' => '813336841',
            'website' => 'bahali.org',
            'social_links' => null,
            'profile_photo' => 'providers/photos/TVUobc2nh9oXtp7pJbZCiiaZV0PVDBVrjTVGA73x.png',
            'additional_photos' => json_encode([]),
            'accessibility' => json_encode(['Wheelchair Accessible', 'Other']),
            'status' => 'pending',
            'note' => null,
            'consent_accurate' => true,
            'consent_notify' => true,
            'consent_no_endorsement' => true,
            'consent_public' => true,
            'reviewed_at' => null,
            'created_at' => '2026-07-23 23:19:34',
            'updated_at' => '2026-07-23 23:19:34',
        ]);

        DB::table('provider_support_areas')->insert([
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Panic Attacks',
                'created_at' => '2026-07-23 23:19:34',
                'updated_at' => '2026-07-23 23:19:34',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Grief & Loss',
                'created_at' => '2026-07-23 23:19:34',
                'updated_at' => '2026-07-23 23:19:34',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Mental & Emotional Well-Being',
                'area' => 'Trauma & Recovery',
                'created_at' => '2026-07-23 23:19:34',
                'updated_at' => '2026-07-23 23:19:34',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Relationships & Family',
                'area' => 'Couples & Relationship Counseling',
                'created_at' => '2026-07-23 23:19:34',
                'updated_at' => '2026-07-23 23:19:34',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Children, Teens & Families',
                'area' => 'ADHD',
                'created_at' => '2026-07-23 23:19:34',
                'updated_at' => '2026-07-23 23:19:34',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Women\'s Health & Wellness',
                'area' => 'Pregnancy Support',
                'created_at' => '2026-07-23 23:19:34',
                'updated_at' => '2026-07-23 23:19:34',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Men\'s Health & Wellness',
                'area' => 'Relationship Challenges',
                'created_at' => '2026-07-23 23:19:34',
                'updated_at' => '2026-07-23 23:19:34',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Older Adults & Aging',
                'area' => 'Healthy Aging & Older Adult Well-Being',
                'created_at' => '2026-07-23 23:19:34',
                'updated_at' => '2026-07-23 23:19:34',
            ],
            [
                'provider_id' => $providerId,
                'category' => 'Crisis, Trauma & Recovery',
                'area' => 'Suicide Prevention',
                'created_at' => '2026-07-23 23:19:34',
                'updated_at' => '2026-07-23 23:19:34',
            ],
        ]);
    }
}
